config/routes.rb
Rails.application.routes.draw do
  resources :contactlists
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contactlist.rb
class Contactlist < ApplicationRecord
  validates_presence_of :name, :address
  validates_uniqueness_of :phone, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contactlists_controller.rb
class ContactlistsController < ApplicationController
  before_action :set_contactlist, only: %i[ show edit update destroy ]

  # GET /contactlists or /contactlists.json
  def index
    @contactlists = Contactlist.order(created_at: :desc)
  end

  # GET /contactlists/1 or /contactlists/1.json
  def show
  end

  # GET /contactlists/new
  def new
    @contactlist = Contactlist.new
  end

  # GET /contactlists/1/edit
  def edit
  end

  # POST /contactlists or /contactlists.json
  def create
    @contactlist = Contactlist.new(contactlist_params)

    respond_to do |format|
      if @contactlist.save
        format.js
        format.html { redirect_to contactlist_url(@contactlist), notice: "Contactlist was successfully created." }
        format.json { render :show, status: :created, location: @contactlist }

      else
        format.js
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contactlist.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /contactlists/1 or /contactlists/1.json
  def update
    respond_to do |format|
      if @contactlist.update(contactlist_params)

        format.html { redirect_to contactlist_url(@contactlist), notice: "Contactlist was successfully updated." }
        format.json { render :show, status: :ok, location: @contactlist }
        format.js
      else
        format.js
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contactlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactlists/1 or /contactlists/1.json
  def destroy
    @contactlist.destroy

    respond_to do |format|
      format.html { redirect_to contactlists_url, notice: "Contactlist was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contactlist
      @contactlist = Contactlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contactlist_params
      params.require(:contactlist).permit(:name, :phone, :email, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactlists_helper.rb
module ContactlistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contactlists/_contact_row.html.erb
<tr id="contactRow_<%= contactlist.id %>" style="background-color: #ffd9e5">
  <td class="align-middle"><%= contactlist.name %></td>
  <td class="align-middle"><%= contactlist.phone %></td>
  <td class="align-middle"><%= contactlist.email %></td>
  <td class="align-middle"><%= contactlist.address %></td>
  <td>
    <%= link_to raw("<i class=\"fas fa-eye\"></i>"), contactlist, class:"btn btn-info" %>
    <%= link_to raw("<i class=\"fas fa-edit\"></i>"), edit_contactlist_path(contactlist), class:"btn btn-primary", data:{ bs_toggle: 'modal', bs_target: '#editcontactmodal', remote: true} %>
    <%= link_to raw("<i class=\"fas fa-trash-alt\"></i>"), contactlist, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger", remote: true  %>
  </td>
</tr>

app/views/contactlists/_form.html.erb
<%= form_with(model: contactlist, local: false) do |form| %>
<div class="modal-body">
  <% if contactlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contactlist.errors.count, "error") %> prohibited this contactlist from being saved:</h2>

      <ul>
        <% contactlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-floating mb-3 mt-3">
      <%= form.text_field :name, class:"form-control", placeholder:"Name"%>
      <label>Name </label>
    </div>

    <div class="form-floating mb-3 mt-3">
      <%= form.text_field :phone, class:"form-control", placeholder:"Phone"%>
      <label>Phone</label>
    </div>

    <div class="form-floating mb-3 mt-3">
      <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
      <label>Email</label>
    </div>

  <div class="form-floating mb-3 mt-3">
      <%= form.text_field :address, class:"form-control", placeholder:"Address" %>
      <label class="col-lg-1 col-form-label">Address</label>
    </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Close</button>
  <%= form.submit class:"btn btn-primary float-right" %>
</div>
<% end %>

app/views/contactlists/create.js.erb
<% if @contactlist.errors.any?%>
  alert('Invalid Details');
<% else %>
  $("#contactTable").prepend("<%= escape_javascript render('contact_row', contactlist: @contactlist) %>");
  $(".close-modal").click();
<% end %>

app/views/contactlists/destroy.js.erb
$("#contactRow_<%= @contactlist.id %>").remove();

app/views/contactlists/edit.html.erb
<h1>Edit <%= @contactlist.name%> Contact </h1>

<%= render 'form', contactlist: @contactlist %>

<%= link_to 'Show', @contactlist, class:"btn btn-secondary" %>
<%= link_to 'Back', contactlists_path, class:"btn btn-primary" %>

app/views/contactlists/edit.js.erb
$("#editcontactForm").html("<%= escape_javascript render('form', contactlist: @contactlist) %>");

app/views/contactlists/index.html.erb
<table id="contactlists" class="table table-borderless">
  <thead>
    <tr style="background-color: #ff91b4">
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody class="table-striped" id="contactTable">
    <% @contactlists.each do |contactlist| %>
      <%= render 'contact_row', contactlist: contactlist %>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Contact', new_contactlist_path, class:'btn btn-primary', data:{ bs_toggle: 'modal', bs_target: '#newcontactmodal', remote: true} %>


<!-- Modal New-->
<div class="modal fade" id="newcontactmodal" tabindex="-1" aria-labelledby="newcontactmodalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newcontactmodalLabel">New Contact</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="newcontactForm">
      </div>
    </div>
  </div>
</div>

<!-- Modal Edit-->
<div class="modal fade" id="editcontactmodal" tabindex="-1" aria-labelledby="editcontactmodalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editcontactmodalLabel">Edit Contact</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="editcontactForm">

      </div>

    </div>
  </div>
</div>

app/views/contactlists/new.html.erb
<h1>Add Contact</h1>

<%= render 'form', contactlist: @contactlist %>

<%= link_to 'Back', contactlists_path, class:"btn btn-dark " %>

app/views/contactlists/new.js.erb
$("#newcontactForm").html("<%= escape_javascript render('form', contactlist: @contactlist) %>");

app/views/contactlists/show.html.erb
<div style="background:#ffabc5; padding: 2rem 1rem; margin-bottom: 2rem">
  <h1 class="display-4"><%= @contactlist.name %></h1>
  <p>
    <strong>Here <%= @contactlist.name %> Contact Information</strong>
  </p>

  <p>
    <small>
      <%= @contactlist.phone %> <br>
      <%= @contactlist.email %><br>
      <%= @contactlist.address %>
    </small>
</p>
  <hr class="my-4">
  <%= link_to 'Back', contactlists_path, class:'btn btn-dark'  %>

</div>

app/views/contactlists/update.js.erb
<% if @contactlist.errors.any?%>
  alert('Invalid Details');
<% else %>
  $("#contactRow_<%= @contactlist.id %>").replaceWith("<%= escape_javascript render('contact_row', contactlist: @contactlist) %>");
  $(".close-modal").click();
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark rounded" style="background:#ff91b4">
  <div class="container-fluid">
    <%= link_to  image_tag("/contact.png",:size => "30x30")+raw("<span> Contact Apps</span>"), root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Contact List", contactlists_path, class:"nav-link" %>
      </li>

    </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div style="background:#ffabc5; padding: 2rem 1rem; margin-bottom: 2rem !important">
  <h1 class="display-4">Contact Apps</h1>
  <p class="lead">You can saving your friend contact here :)</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>Contact</title>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <div class="container-fluid">

      <div class="mb-2">
        <%=render 'home/header' %>
      </div>

      <% if notice %>
        <%=render 'layouts/alerts' %>
      <%end%>

      <%= yield %>

    </div>


  </body>
</html>